### ISSUE TITLE
deprecated features in y2clerk

### ISSUE THREAD

**Issue by coleton-y2** [y2analytics/y2clerk#16]
I was prompted to report this error to Github

Code: 
frequencies <- responses %>%
+   group_by(Market) %>% 
+   freqs(Q7a_1) %>% 
+   filter(!is.na(label)) %>% 
+   sig_test_y2(
+     banner_var = Market,
+     dataset = responses,
+     layout = "wide"
+   )

Warning : 
Specifying the `id_cols` argument by position was deprecated in tidyr 1.3.0.
ℹ Please explicitly name `id_cols`, like `id_cols = label`.
ℹ The deprecated feature was likely used in the y2clerk package.

**Comment by canyenheimuli** [comment]
Fixed with latest updated to sig_test in dplyr 0.6.11
